org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,)
forge_version=47.4.16
forge_version_range=[47,)
ribbits_version_range=[1.20.1-Forge-3.0.0,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

mod_id=wandering_ribbit
mod_name=Wandering Ribbit
mod_license=All Rights Reserved
mod_version=4.1
mod_group_id=com.cosmicbarri
mod_credits=To all the original Ribbits mod team
mod_authors=cosmic-barri
mod_description=Adds the wandering ribbit, a little merchant that will sell a map to locate the nearest ribbit village and other things.
geckolib_version=4.8.3
